### ISSUE TITLE
PHP 7.x support?

### ISSUE THREAD

**Issue by Neustradamus** [cdgco/home#3]
It is possible to add the PHP 7.x support?

Currently:
- https://www.php.net/supported-versions.php

**Comment by cdgco** [comment]
Sure, I will look into adding PHP 7. 

That should be fairly easy, however some integrations like the weather underground API have been deprecated since I last updated this project, so it may take a while before I have the integrations back up and running.

**Comment by cdgco** [comment]
a531a39: While this update should fix everything, there are likely some small bugs I have not found yet. If you run into any, let me know and I'll fix them.

**Comment by Neustradamus** [comment]
@cdgco: Thanks!
